# Generated by Django 5.1.3 on 2024-12-15 09:39

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='fallback.png', upload_to='images/featured_product/logos/')),
                ('mobile_cover_image', models.ImageField(blank=True, default='fallback.png', upload_to='images/featured_product/main_image')),
                ('title', models.CharField(max_length=255)),
                ('discription', models.CharField(default=0, max_length=511)),
                ('button_url', models.CharField(max_length=1500)),
                ('desktop_cover_image', models.ImageField(blank=True, default='fallback.png', upload_to='images/featured_product/main_image')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('preview_image', models.ImageField(blank=True, upload_to='images/game_images/')),
                ('big_preview_image', models.ImageField(blank=True, upload_to='images/game_images/')),
                ('game_edition', models.CharField(default=1, max_length=255)),
                ('size', models.IntegerField()),
                ('logo', models.ImageField(blank=True, default='fallback.png', upload_to='images/games/logo')),
                ('discription', tinymce.models.HTMLField()),
                ('slug', models.SlugField(unique=True)),
                ('developer', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('minimum_os', models.CharField(max_length=255)),
                ('minimum_processor', models.CharField(max_length=255)),
                ('minimum_memory', models.CharField(max_length=255)),
                ('minimum_storage', models.CharField(max_length=255)),
                ('minimum_graphics', models.CharField(max_length=255)),
                ('minimum_other', models.CharField(max_length=255, null=True)),
                ('maximum_os', models.CharField(max_length=255)),
                ('maximum_processor', models.CharField(max_length=255)),
                ('maximum_memory', models.CharField(max_length=255)),
                ('maximum_storage', models.CharField(max_length=255)),
                ('maximum_graphics', models.CharField(max_length=255)),
                ('maximum_other', models.CharField(max_length=255, null=True)),
                ('image_1', models.ImageField(blank=True, upload_to='images/game_images/')),
                ('image_2', models.ImageField(blank=True, upload_to='images/game_images/')),
                ('image_3', models.ImageField(blank=True, upload_to='images/game_images/')),
                ('image_4', models.ImageField(blank=True, upload_to='images/game_images/')),
                ('image_5', models.ImageField(blank=True, upload_to='images/game_images/')),
                ('image_6', models.ImageField(blank=True, upload_to='images/game_images/')),
                ('video', models.ImageField(blank=True, upload_to='images/game_videos/')),
            ],
        ),
        migrations.CreateModel(
            name='StorageDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('usable_capacity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
