# Generated by Django 5.1.3 on 2024-12-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_game_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagedevice',
            name='discription',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/hard_images/'),
        ),
    ]
