# Generated by Django 5.1.3 on 2024-12-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_storagedevice_discription_storagedevice_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storagedevice',
            old_name='name',
            new_name='size',
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
