# Generated by Django 5.1.3 on 2024-12-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='video',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
