# Generated by Django 5.1.3 on 2024-12-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_game_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagedevice',
            name='discount_price',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
