# Generated by Django 5.1.3 on 2024-12-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_game_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_old',
            field=models.BooleanField(default=False),
        ),
    ]
