# Generated by Django 5.1.3 on 2024-12-31 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_game_is_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproducts',
            name='discription',
            field=models.CharField(blank=True, default=0, max_length=511),
        ),
        migrations.AlterField(
            model_name='featuredproducts',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
