# Generated by Django 5.1.3 on 2025-01-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_featuredproducts_discription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredproducts',
            name='button_title',
            field=models.CharField(default='Learn More', max_length=25),
        ),
    ]
