# Generated by Django 5.2.5 on 2025-08-12 14:32

import django.core.validators
import django.db.models.deletion
import shop.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_company_genre_cart_order_product_orderitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(default='LKR', max_length=3),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=shop.models.generate_ticket_ref, editable=False, max_length=20, unique=True)),
                ('source', models.CharField(choices=[('DARAZ', 'Daraz'), ('VIRTUAL_LAB', 'Virtual Lab website')], max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('video', models.FileField(blank=True, help_text='Upload a single video file (mp4, mov, m4v, webm, avi).', null=True, upload_to='tickets/%Y/%m/%d/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'm4v', 'webm', 'avi'])])),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High')], default='NORMAL', max_length=10)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='shop.order')),
                ('users', models.ManyToManyField(blank=True, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='tickets/%Y/%m/%d/photos/')),
                ('alt_text', models.CharField(blank=True, max_length=150)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='shop.ticket')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
