# Generated by Django 5.2.5 on 2025-08-12 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_order_currency_ticket_ticketphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('slot', models.CharField(choices=[('09:00-10:00', '9:00–10:00 AM'), ('21:00-22:00', '9:00–10:00 PM'), ('22:00-23:00', '10:00–11:00 PM')], max_length=11)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='shop.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reserved_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'slot'],
                'indexes': [models.Index(fields=['date', 'slot'], name='shop_reserv_date_cfaaa8_idx')],
                'unique_together': {('date', 'slot')},
            },
        ),
    ]
