# Generated by Django 5.2.5 on 2025-08-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_reservedslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='daraz_order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='daraz_order_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
