# Generated by Django 5.2.5 on 2025-08-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_gamerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='edition',
            field=models.CharField(default='Standard Edition', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(default='LKR', max_length=3),
        ),
    ]
