# Generated by Django 5.2.5 on 2025-08-13 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_edition_alter_product_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dlcs',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_dlc',
        ),
        migrations.CreateModel(
            name='DLC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='products/dlcs/%Y/%m/%d/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dlcs', to='shop.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
