# Generated by Django 5.2.5 on 2025-08-17 12:38

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_storagedevice_remove_product_dlcs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_line1',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='address line 1'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_line2',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='address line 2'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_no',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='address number'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='postal code'),
        ),
        migrations.AlterField(
            model_name='dlc',
            name='image',
            field=models.ImageField(upload_to=shop.models.product_image_upload_to),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=shop.models.product_image_upload_to),
        ),
    ]
