# Generated by Django 5.2.5 on 2025-08-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_user_address_line1_user_address_line2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Genie customer id'),
        ),
    ]
