# Generated by Django 5.2.5 on 2025-08-19 16:18

import django.core.validators
import django.db.models.deletion
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order_storage_device_name_order_storage_device_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('main_image', models.ImageField(upload_to=shop.models.blog_cover_upload_to)),
                ('category', models.CharField(choices=[('stories', 'Game Stories'), ('news', 'Gaming News'), ('tech', 'Tech Insights')], max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('reading_time_minutes', models.PositiveSmallIntegerField(help_text='Approximate minutes to read', validators=[django.core.validators.MinValueValidator(1)])),
                ('content_si', models.TextField(help_text='Content in Sinhala')),
                ('content_en', models.TextField(help_text='Content in English')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='shop_blog_slug_69ea88_idx'), models.Index(fields=['category'], name='shop_blog_categor_1751ba_idx'), models.Index(fields=['-created_at'], name='shop_blog_created_13cd33_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlogPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=shop.models.blog_photo_upload_to)),
                ('alt_text', models.CharField(blank=True, max_length=150)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='shop.blog')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
