# Generated by Django 5.2.5 on 2026-03-30 06:43

import django.core.validators
import django.db.models.deletion
import shop.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_blog_blogphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='The order in which this question appears (e.g., 1, 2, 3).')),
            ],
            options={
                'ordering': ['quiz', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('quiz_number', models.PositiveIntegerField(help_text='A unique number for this quiz, e.g., 101.', unique=True)),
                ('description', models.TextField(blank=True, help_text='A brief description of the quiz topic.')),
                ('time_limit_minutes', models.PositiveIntegerField(default=30, help_text='Duration of the quiz in minutes.', validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'ordering': ['quiz_number'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='addon_for',
            field=models.ForeignKey(blank=True, help_text='Links this product as an add-on to a main product (e.g., a game box for a game).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='shop.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_addon_only',
            field=models.BooleanField(default=False, help_text='If true, this product will not appear on the main shop page and is only sold as an add-on.'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_cracked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_cod_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='steam_email',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='steam email'),
        ),
        migrations.AddField(
            model_name='user',
            name='steam_username',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='steam username'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Card'), ('BANK_TRANSFER', 'Bank transfer'), ('COD', 'Cash On Delivery')], default='CARD', max_length=20),
        ),
        migrations.CreateModel(
            name='OfflineGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remaining_tickets', models.PositiveIntegerField(default=1, help_text='How many activation tickets can be generated for this.')),
                ('product', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='offline_game_config', to='shop.product')),
            ],
            options={
                'verbose_name': 'Offline Game',
                'verbose_name_plural': 'Offline Games',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False, help_text='Mark this if it is the correct answer.')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='shop.question')),
            ],
            options={
                'ordering': ['question', 'id'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='shop.quiz'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_number', models.PositiveIntegerField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, help_text='Set when the user submits the quiz.', null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='shop.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'quiz', '-attempt_number'],
                'unique_together': {('user', 'quiz', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username_display', models.CharField(help_text="Public display name, e.g. 'Kasun P.' or 'GamerPro_LK'", max_length=100)),
                ('review', models.TextField(help_text='The review text shown on the homepage.')),
                ('stars', models.PositiveSmallIntegerField(help_text='Star rating from 1 to 5.', validators=[django.core.validators.MinValueValidator(1)])),
                ('image_1', models.ImageField(blank=True, help_text='First review photo (optional) — e.g. unboxing, gameplay screenshot.', null=True, upload_to=shop.models.review_image_upload_to)),
                ('image_2', models.ImageField(blank=True, help_text='Second review photo (optional).', null=True, upload_to=shop.models.review_image_upload_to)),
                ('is_active', models.BooleanField(default=True, help_text='Only active reviews are shown on the homepage.')),
                ('product', models.ForeignKey(help_text='The product this review is about.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.product')),
                ('user', models.ForeignKey(help_text='The user who wrote this review.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivationTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activation_code', models.CharField(default=shop.models.generate_activation_code, editable=False, max_length=19, unique=True)),
                ('status', models.CharField(choices=[('PAYMENT_PENDING', 'Payment Pending'), ('COD_PAYMENT_PENDING', 'COD Payment Pending'), ('ACTIVATED', 'Activated'), ('EXPIRED', 'Expired')], default='PAYMENT_PENDING', max_length=20)),
                ('payment_slip', models.ImageField(blank=True, help_text='Bank slip uploaded by the user as proof of payment.', null=True, upload_to='payment_slips/%Y/%m/')),
                ('remaining_attempts', models.PositiveSmallIntegerField(default=2)),
                ('activation_date', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activation_tickets', to='shop.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_tickets', to=settings.AUTH_USER_MODEL)),
                ('offline_game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activation_tickets', to='shop.offlinegames')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'offline_game', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ActivationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_number', models.PositiveSmallIntegerField()),
                ('topic_en', models.CharField(max_length=255, verbose_name='Topic (English)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('topic_si', models.CharField(blank=True, max_length=255, verbose_name='Topic (Sinhala)')),
                ('description_si', models.TextField(blank=True, verbose_name='Description (Sinhala)')),
                ('is_updated', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='activation_steps/files/')),
                ('video', models.FileField(blank=True, null=True, upload_to='activation_steps/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'm4v', 'webm'])])),
                ('offline_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_steps', to='shop.offlinegames')),
            ],
            options={
                'ordering': ['offline_game', 'step_number'],
                'unique_together': {('offline_game', 'step_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('quiz', 'order')},
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='shop.question')),
                ('quiz_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='shop.quizattempt')),
                ('selected_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_selections', to='shop.choice')),
            ],
            options={
                'unique_together': {('quiz_attempt', 'question')},
            },
        ),
    ]
