"""
Django settings for virtuallab project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from django.conf import settings
from django.conf.urls.static import static
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0k&o=y0cp)o)eja_@s%w1hkkb8=dpz-ob_nc4p!kue95-3mqm)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'tinymce',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shop.apps.ShopConfig',
    'cart.apps.CartConfig',
    'members.apps.MembersConfig',


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'virtuallab.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

            ],
        },
    },
]

WSGI_APPLICATION = 'virtuallab.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'virtuallab',
        'USER': 'root',
        'HOST': 'localhost',
        'PASSWORD': '#Ssassin@3'
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# MEDIA_URL = '/media/'


# STATICFILES_DIRS = [
# os.path.join(BASE_DIR, 'staticfiles')
# ]
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_URL = '/static/'  # URL to access static files
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Directory for collected static files
STATICFILES_DIRS = [
    # Additional static file locations for development
    os.path.join(BASE_DIR, 'static')
]

MEDIA_URL = '/media/'  # URL to access media files
# Directory for uploaded media files
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    "site_header": "Virtual Lab",
    "site_title": "Virtual Lab Admin",

}


TINYMCE_DEFAULT_CONFIG = {
    'height': 600,
    'width': '100%',  # Make it responsive
    'plugins': (
        'advlist autolink lists link image charmap print preview anchor pagebreak spellchecker searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking save table directionality emoticons template paste textcolor'
    ),
    'toolbar1': (
        'undo redo | styleselect | bold italic underline strikethrough | fontselect fontsizeselect | forecolor backcolor | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | table | link image media | code fullscreen'
    ),
    'toolbar2': (
        'print preview | anchor pagebreak | emoticons | insertdatetime | charmap | visualblocks visualchars | searchreplace spellchecker'
    ),
    'menubar': 'file edit view insert format tools table help',
    'fontsize_formats': '8pt 10pt 12pt 14pt 18pt 24pt 36pt 48pt 64pt 72pt',
    'font_formats': (
        'Arial=arial,helvetica,sans-serif; Times New Roman=times new roman,times,serif; Verdana=verdana,geneva,sans-serif; Courier New=courier new,courier,monospace; Roboto=roboto,sans-serif; Comic Sans MS=comic sans ms,sans-serif'
    ),
    'textcolor_map': [
        "000000", "Black",
        "FF0000", "Red",
        "00FF00", "Green",
        "0000FF", "Blue",
        "FFFF00", "Yellow",
        "FFA500", "Orange",
        "800080", "Purple",
        "FFFFFF", "White",
        "808080", "Gray",
    ],
    'templates': [
        {'title': 'Standard Template', 'content': '<p>This is a template</p>'},
        {'title': 'Table Template',
            'content': '<table><tr><th>Heading</th></tr><tr><td>Data</td></tr></table>'},
    ],
    'content_css': [
        'https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css',
    ],
    'branding': False,
}
