# Generated by Django 5.1.3 on 2024-12-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('P', 'Pending'), ('I', 'Identified'), ('C', 'Complete'), ('F', 'Failed')], default='P', max_length=1),
        ),
    ]
