# Generated by Django 5.1.3 on 2024-12-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_address_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_storage_name',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
