# Generated by Django 5.1.3 on 2024-12-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_cart_storage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_storage_name',
            field=models.CharField(max_length=255),
        ),
    ]
