# Generated by Django 5.1.3 on 2024-12-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cart_cart_storage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_storage_category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_storage_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
